// console.log(String(123));
// console.log(String(123.5));
// console.log(String(1234567n));
// console.log(String("text"));
// console.log(String(true));
// console.log(String(null));
// console.log(String(undefined));
// console.log(String(Symbol("text")));
// console.log(String([]));
// console.log(String({}));
// console.log(String([1, 2, 3, 4, 5]));
// console.log(String({ name: 'Amit', age: 34 }));

// console.log(Number(123));
// console.log(Number(123.5));
// console.log(Number(1234567n));
// console.log(Number("text"));
// console.log(Number(true));
// console.log(Number(null));
// console.log(Number(undefined));
// console.log(Number(Symbol("text")));
// console.log(Number([]));
// console.log(Number({}));
// console.log(Number([1, 2, 3, 4, 5]));
// console.log(Number({ name: 'Amit', age: 34 }));

console.log(Boolean(0));
console.log(Boolean(+0));
console.log(Boolean(-0));
console.log(Boolean(-5));
console.log(Boolean(123));
console.log(Boolean(123.5));
console.log(Boolean(1234567n));
console.log(Boolean("text"));
console.log(Boolean(true));
console.log(Boolean(null));
console.log(Boolean(undefined));
console.log(Boolean(Symbol("text")));
console.log(Boolean([]));
console.log(Boolean({}));
console.log(Boolean([1, 2, 3, 4, 5]));
console.log(Boolean({ name: 'Amit', age: 34 }));